apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: workshop

spec:
  limits:
  - defaults:
      cpu: "500m"
      memory: "512Mi"

    defaultRequest:
      cpu: "250m"
      memory: "256Mi"

    type: container

