apiVersion: v1
kind: service
metadata: 
  name: my-pod-service
  labels:
    app:  my-app
  namespace:  fronend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: java
    port: 8080
    targetport: 8080
    protocol: TCP
  selector:
    app:  my-app